apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: kafka-topics-
spec:
  entrypoint: create-kafka-topics
  arguments:
    parameters:
    - name: kafka-bootstrap-servers
    - name: topic1-name
      value: "poke-orders"
    - name: topic2-name
      value: "poke-orders-state"
    - name: topic1-replication-factor
      value: "1"
    - name: topic2-replication-factor
      value: "3"
  templates:
  - name: create-kafka-topics
    inputs:
      parameters:
      - name: kafka-bootstrap-servers
      - name: topic1-name
      - name: topic2-name
      - name: topic1-replication-factor
      - name: topic2-replication-factor
    steps:
    - - name: create-and-describe-topic1
        template: create-and-describe-topic
        arguments:
          parameters:
          - name: topic-name
            value: "{{inputs.parameters.topic1-name}}"
          - name: kafka-bootstrap-servers
            value: "{{inputs.parameters.kafka-bootstrap-servers}}"
          - name: replication-factor
            value: "{{inputs.parameters.topic1-replication-factor}}"
      - name: create-and-describe-topic2
        template: create-and-describe-topic
        arguments:
          parameters:
          - name: topic-name
            value: "{{inputs.parameters.topic2-name}}"
          - name: kafka-bootstrap-servers
            value: "{{inputs.parameters.kafka-bootstrap-servers}}"
          - name: replication-factor
            value: "{{inputs.parameters.topic2-replication-factor}}"

  - name: create-and-describe-topic
    inputs:
      parameters:
      - name: topic-name
      - name: kafka-bootstrap-servers
      - name: replication-factor
    steps:
    - - name: create-topic
        template: create-topic
        arguments:
          parameters:
          - name: topic-name
            value: "{{inputs.parameters.topic-name}}"
          - name: kafka-bootstrap-servers
            value: "{{inputs.parameters.kafka-bootstrap-servers}}"
          - name: replication-factor
            value: "{{inputs.parameters.replication-factor}}"
        continueOn:
          failed: true
    - - name: describe-topic
        template: describe-topic
        arguments:
          parameters:
          - name: topic-name
            value: "{{inputs.parameters.topic-name}}"
          - name: kafka-bootstrap-servers
            value: "{{inputs.parameters.kafka-bootstrap-servers}}"
        continueOn:
          failed: true

  - name: create-topic
    inputs:
      parameters:
      - name: topic-name
      - name: kafka-bootstrap-servers
      - name: replication-factor
    container:
      image: confluentinc/cp-kafka:latest
      command: ["/bin/sh", "-c"]
      args: ["kafka-topics --create --topic {{inputs.parameters.topic-name}} --partitions 1 --replication-factor {{inputs.parameters.replication-factor}} --bootstrap-server {{inputs.parameters.kafka-bootstrap-servers}}"]

  - name: describe-topic
    inputs:
      parameters:
      - name: topic-name
      - name: kafka-bootstrap-servers
    container:
      image: confluentinc/cp-kafka:latest
      command: ["/bin/sh", "-c"]
      args: ["kafka-topics --describe --topic {{inputs.parameters.topic-name}} --bootstrap-server {{inputs.parameters.kafka-bootstrap-servers}}"]