name: Build and Push Chaos Experiments Image

on:
  push:
    tags:
      - '*-chaos'

jobs:
  build-and-push-experiments:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: linux/amd64,linux/arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push experiments image
      uses: docker/build-push-action@v3
      with:
        context: ./experiments
        file: ./experiments/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/kafka-chaos-experiments:${{ github.ref_name }}
          ${{ secrets.DOCKER_USERNAME }}/kafka-chaos-experiments:latest